services:
  db:
    environment:
      - POSTGRES_PASSWORD=F0r3v3r
  challenge:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
  trail-circuit:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"
  track:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/app"